site_name: "Codacy Chart"
use_directory_urls: true
theme:
  logo: 'images/codacy-logo.svg'
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
copyright: "Codacy"
strict: true
plugins:
- search
markdown_extensions:
- admonition
- codehilite
- pymdownx.inlinehilite
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.superfences
- toc:
    permalink: true