# Project information
site_name: chart
site_url: https://codacy.github.io/chart/

# Configuration
theme:
    logo: 'images/codacy-logo.svg'
    name: 'material'
    palette:
        primary: 'indigo'
        accent: 'indigo'

extra_css:
  - 'css/extra.css'
  - 'css/version-select.css'
extra_javascript:
  - 'js/extra.js'
  - 'js/version-select.js'
strict: true
use_directory_urls: true

# Copyright
copyright: '© <a href="https://www.codacy.com/">Codacy</a>'

# Plugins and extensions
plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - attr_list
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tasklist:
        custom_checkbox: true
  - toc:
        permalink: true

# Table of contents
nav:
  - index.md
  - requirements.md
  - "Setting up Kubernetes":
      - infrastructure/eks-quickstart.md
      - infrastructure/microk8s-quickstart.md
  - "Configuring Codacy":
      - "Integrations":
          - configuration/integrations/github-cloud.md
          - configuration/integrations/github-enterprise.md
          - configuration/integrations/github-app-create.md
          - configuration/integrations/gitlab-cloud.md
          - configuration/integrations/gitlab-enterprise.md
          - configuration/integrations/bitbucket-cloud.md
          - configuration/integrations/bitbucket-server.md
          - configuration/integrations/email.md
      - configuration/tls-ingress-aws.md
      - configuration/monitoring.md
  - "Maintenance and operations":
      - maintenance/upgrade.md
      - maintenance/uninstall.md
      - maintenance/database.md
  - "Troubleshooting":
      - troubleshoot/troubleshoot.md
      - troubleshoot/logs-collect.md
      - troubleshoot/k8s-cheatsheet.md
