# Project information
site_name: "Codacy Chart"

# Configuration
theme:
  logo: 'images/codacy-logo.svg'
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'

strict: true
use_directory_urls: true

# Copyright
copyright: '© <a href="https://www.codacy.com/">Codacy</a>'

# Plugins and extensions
plugins:
- search

markdown_extensions:
- admonition
- codehilite
- pymdownx.inlinehilite
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.superfences
- toc:
    permalink: true
