site_name: "Codacy Chart"
use_directory_urls: true
theme:
  logo: 'images/codacy-logo.svg'
  name: 'material'
  palette:
    primary: 'indigo'
    accent: 'indigo'
extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
  - 'javascripts/extra.js'
copyright: "Codacy"
strict: true
plugins:
- search
markdown_extensions:
- admonition
- codehilite
- pymdownx.inlinehilite
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.superfences
- toc:
    permalink: true

# Table of contents
nav:
  - index.md
  - requirements.md
  - "1. Setting up the Kubernetes infrastructure":
    - infrastructure/eks-quickstart.md
    - infrastructure/aks-quickstart.md
    - infrastructure/microk8s-quickstart.md
  - "2. Installing Codacy": install.md
  - "3. Post-install configuration":
    - configuration/git-providers/github-cloud.md
    - configuration/git-providers/github-enterprise.md
    - configuration/git-providers/gitlab-enterprise.md
    - configuration/git-providers/bitbucket-enterprise.md
    - configuration/logging.md
    - configuration/monitoring.md
  - "Extra":
    - extra/upgrade.md
    - extra/uninstall.md
    - extra/database.md
    - extra/k8s-cheatsheet.md
    - extra/logs-collect.md
