global:
  github:
    enabled: "true"
    login: "true"

  githubEnterprise:
    enabled: "true"
    login: "true"
    hostname: "github.dev.codacy.org"
    port: 443
    protocol: "https"
    disableSSL: "true"
    isPrivateMode: "true"

  gitlab:
    enabled: "true"
    login: "true"

  gitlabEnterprise:
    enabled: "true"
    login: "true"
    hostname: "gitlab.dev.codacy.org"
    protocol: "http"
    port: 80

  bitbucket:
    enabled: "true"
    login: "true"

  bitbucketEnterprise:
    enabled: "true"
    login: "true"
    hostname: "bitbucket-server.codacy.org"
    protocol: "http"
    port: 7990

  workers:
    config:
      dedicatedMax: 20
      inactivityTimeout: 30
      analysis:
        maxFileSizeBytes: 150000
        # These values are in seconds
        pluginTimeout:
          min: 300
          max: 900

  crow:
    config:
      passwordAuth:
        enable: true
        username: <--- crow-username --->
        password: <--- crow-password --->

  activitiesdb:
    create: false
    postgresqlUsername: <--- codacy-db-username --->
    postgresqlDatabase: activities # You need to create the DB manually
    postgresqlPassword: <--- codacy-db-password --->
    host: <--- codacy-db-host --->
    service:
      port: <--- codacy-db-port --->
  hotspotsdb:
    create: false
    postgresqlUsername: <--- codacy-db-username --->
    postgresqlDatabase: hotspots # You need to create the DB manually
    postgresqlPassword: <--- codacy-db-password --->
    host: <--- codacy-db-host --->
    service:
      port: <--- codacy-db-port --->
  crowdb:
    create: false
    host: <--- codacy-db-host --->
    postgresqlUsername: <--- codacy-db-username --->
    postgresqlDatabase: crow # You need to create the DB manually
    postgresqlPassword: <--- codacy-db-password --->
    service:
      port: <--- codacy-db-port --->
  listenerdb:
    create: false
    postgresqlUsername: <--- codacy-db-username --->
    postgresqlDatabase: listener # You need to create the DB manually
    postgresqlPassword: <--- codacy-db-password --->
    host: <--- codacy-db-host --->
    service:
      port: <--- codacy-db-port --->

  metrics:
    serviceMonitor:
      enabled: true
    grafana:
      enabled: true
      label: "grafana_dashboard"

codacy-ingress:
  create: true
  ingress:
    hostname:
      app: <codacy-app.dns.internal>
      api: <codacy-api.dns.internal>
    spa:
      serviceName: codacy-spa # this will be moved to the ingress default configs when the spa is released

codacy-api:
  replicaCount: 2
  service:
    type: ClusterIP


portal:
  replicaCount: 1

activities:
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5
  activitiesdb: {}

remote-provider-service:
  replicaCount: 1
  metrics:
    serviceMonitor:
      enabled: true

hotspots-api:
  replicaCount: 1
  hotspotsdb: {}

hotspots-worker:
  replicaCount: 1

listener:
  replicaCount: 1
  listenerdb:
    create: false
  persistence:
    claim:
      size: 140Gi
  nfsserverprovisioner:
    enabled: true
    persistence:
      enabled: true
      size: 200Gi
  listenerdb: {}

core:
  replicaCount: 1

engine:
  replicaCount: 1
  metrics:
    serviceMonitor:
      enabled: true

codacy-tools:
  replicaCount: 1

worker-manager:
  replicaCount: 1
  config:
    workers:
      dedicatedMax: 20
      inactivityTimeout: 30
      analysis:
        podDebugInfo: true
  grafana:
    grafana_dashboards:
      enabled: true

fluentdoperator:
  enabled: true
  expirationDays: 15

crow:
  replicaCount: 1
  config:
    play:
      http:
        context: "/monitoring"
    passwordAuth: {}
  crowdb: {}

rabbitmq-ha:
  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
    prometheusRule:
      enabled: true
      namespace: "monitoring"
      rules:
        - alert: RabbitmqDown
          expr: rabbitmq_up{service="{{ template "rabbitmq.fullname" . }}"} == 0
          for: 5m
          labels:
            severity: error
          annotations:
            summary: Rabbitmq down (instance {{ "{{ $labels.instance }}" }})
            description: RabbitMQ node down
        - alert: ClusterDown
          expr: |
            sum(rabbitmq_running{service="{{ template "rabbitmq.fullname" . }}"})
            < {{ .Values.replicaCount }}
          for: 5m
          labels:
            severity: error
          annotations:
            summary: Cluster down (instance {{ "{{ $labels.instance }}" }})
            description: |
                Less than {{ .Values.replicaCount }} nodes running in RabbitMQ cluster
                VALUE = {{ "{{ $value }}" }}
        - alert: ClusterPartition
          expr: rabbitmq_partitions{service="{{ template "rabbitmq.fullname" . }}"} > 0
          for: 5m
          labels:
            severity: error
          annotations:
            summary: Cluster partition (instance {{ "{{ $labels.instance }}" }})
            description: |
                Cluster partition
                VALUE = {{ "{{ $value }}" }}
        - alert: OutOfMemory
          expr: |
            rabbitmq_node_mem_used{service="{{ template "rabbitmq.fullname" . }}"}
            / rabbitmq_node_mem_limit{service="{{ template "rabbitmq.fullname" . }}"}
            * 100 > 90
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Out of memory (instance {{ "{{ $labels.instance }}" }})
            description: |
                Memory available for RabbmitMQ is low (< 10%)\n  VALUE = {{ "{{ $value }}" }}
                LABELS: {{ "{{ $labels }}" }}
        - alert: TooManyConnections
          expr: rabbitmq_connectionsTotal{service="{{ template "rabbitmq.fullname" . }}"} > 1000
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Too many connections (instance {{ "{{ $labels.instance }}" }})
            description: |
                RabbitMQ instance has too many connections (> 1000)
                VALUE = {{ "{{ $value }}" }}\n  LABELS: {{ "{{ $labels }}" }}