global:
  github:
    enabled: "true"
    login: "true"

  githubEnterprise:
    enabled: "true"
    login: "true"
    hostname: "github.dev.codacy.org"
    port: 443
    protocol: "https"
    disableSSL: "true"
    isPrivateMode: "true"

  gitlab:
    enabled: "true"
    login: "true"

  gitlabEnterprise:
    enabled: "true"
    login: "true"
    hostname: "gitlab.dev.codacy.org"
    protocol: "http"
    port: 80

  bitbucket:
    enabled: "true"
    login: "true"

  bitbucketEnterprise:
    enabled: "true"
    login: "true"
    hostname: "bitbucket-server.codacy.org"
    protocol: "http"
    port: 7990

  config:
    workers:
      analysis:
        maxFileSizeBytes: 150000
        # These values are in seconds
        pluginTimeout:
          min: 300
          max: 900

codacy-ingress:
  create: true
  ingress:
    hostname:
      app: <codacy-app.dns.internal>
      api: <codacy-api.dns.internal>
    spa:
      serviceName: codacy-spa # this will be moved to the ingress default configs when the spa is released

codacy-api:
  replicaCount: 2
  service:
    type: ClusterIP
  metrics:
    serviceMonitor:
      enabled: true
    grafana_dashboards:
      enabled: true

portal:
  replicaCount: 1

activities:
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5

remote-provider-service:
  replicaCount: 1
  metrics:
    serviceMonitor:
      enabled: true

hotspots-api:
  replicaCount: 1

hotspots-worker:
  replicaCount: 1

listener:
  replicaCount: 1
  listenerdb:
    create: false
  persistence:
    claim:
      size: 140Gi
  nfsserverprovisioner:
    enabled: true
    persistence:
      enabled: true
      size: 200Gi
  grafana:
    grafana_dashboards:
      enabled: true

core:
  replicaCount: 1

engine:
  replicaCount: 1
  metrics:
    serviceMonitor:
      enabled: true

codacy-tools:
  replicaCount: 1

worker-manager:
  replicaCount: 1
  config:
    workers:
      dedicatedMax: 20
      inactivityTimeout: 30
  grafana:
    grafana_dashboards:
      enabled: true

fluentdoperator:
  enabled: true

crow:
  replicaCount: 1
  fullnameOverride: codacy-crow
  config:
    play:
      http:
        context: "/monitoring"
    passwordAuth:
      password: "PLEASE_CHANGE_ME"

