create: true
rabbitmqUsername: rabbitmq
rabbitmqPassword: rabbitmq
rabbitmqvHost: "/"
host: codacy-rabbitmq-ha
port: 5672
ssl: false
timeout: 15s

fullnameOverride: codacy-rabbitmq-ha
prometheus:
  operator:
    enabled: false