version: 2.1

orbs:
  codacy: codacy/base@1.0.1

references:

  default_doks_image: &default_doks_image
    docker:
      - image: codacy/ci-do:0.2.3
    working_directory: ~/workdir/

  qa_automation_image: &qa_automation_image
    docker:
      - image: codacy/qa-automation-test-runner:latest
      - image: circleci/openjdk:8u151-jdk
        environment:
          MAVEN_OPTS: -showversion -Xms256m -Xmx512m
          SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
      - image: selenium/standalone-chrome:3.141.0
        environment:
          JAVA_OPTS: -Xss256m -Xmx512m
          MAVEN_OPTS: -showversion -Xms256m -Xmx512m
      
    working_directory: ~/workdir/
  
  # doks node types can be found here https://developers.digitalocean.com/documentation/v2/
  dev_environment: &dev_environment
    DOKS_CLUSTER_NAME: codacy-doks-cluster-dev
    DO_TF_WORKSPACE: dev
    RELEASE_NAME: codacy
    NAMESPACE: codacy
    NODE_TYPE: s-20vcpu-96gb
    K8S_VERSION: 1.14
    NUM_NODES: 5

  nightly_environment: &nightly_environment
    DOKS_CLUSTER_NAME: codacy-doks-cluster-release
    DO_TF_WORKSPACE: release
    RELEASE_NAME: codacy-nightly
    NAMESPACE: codacy-nightly
    NODE_TYPE: s-20vcpu-96gb
    K8S_VERSION: 1.15
    NUM_NODES: 4
  
  release_environment: &release_environment
    DOKS_CLUSTER_NAME: codacy-doks-cluster-release
    DO_TF_WORKSPACE: release
    RELEASE_NAME: codacy-release
    NAMESPACE: codacy-release
    NODE_TYPE: s-20vcpu-96gb
    K8S_VERSION: 1.15
    NUM_NODES: 4

  qa_environment_nightly: &qa_environment_nightly
    PROJECT_NAME: codacy-chart
    TEST_ENVIRONMENT_TYPE: dev
    TEST_PATH: Suite/API/DEV.xml
    TEST_NAME: api
    LAUNCH_NAME: API_DEV_NIGHTLY_DOKS
    LAUNCH_DESCRIPTION: 'Automated Tests Ran by CircleCI'
    LAUNCH_TAG: CIRCLECI;API;DEV;DIGITALOCEAN
    RP_ENDPOINT: https://reportportal.staging.codacy.org
    HUB_URL: http://localhost:4444/wd/hub

  unstable_helm_channel: &unstable_helm_channel
    CHANNEL: unstable

  incubator_helm_channel: &incubator_helm_channel
    CHANNEL: incubator

  stable_helm_channel: &stable_helm_channel
    CHANNEL: stable

  doctl_authenticate: &doctl_authenticate
    run:
      name: "Setup DO Credentials"
      command: doctl auth init -t $DO_TOKEN &>/dev/null
  
  purge_cluster: &purge_cluster
    <<: *default_doks_image
    steps:
      - checkout
      - <<: *doctl_authenticate
      - deploy:
          name: "Purge Cluster"
          command: make -C .doks/ remove_codacy  
  
  deploy_to_cluster: &deploy_to_cluster
    steps:
      - checkout
      - run:
          name: "Helm lint"
          command: helm lint codacy/
      - <<: *doctl_authenticate
      - deploy:
          name: Install Codacy
          command: make -C .doks/ deploy_to_doks

  validate_deployment_status_on_cluster: &validate_deployment_status_on_cluster
    steps:
      - attach_workspace:
          at: ~/
      - <<: *doctl_authenticate
      - run:
          name: "Validate deployment status"
          command: |
            set -e
            doctl kubernetes cluster kubeconfig save "$DOKS_CLUSTER_NAME" --set-current-context
            DEPLOYMENTS=$(kubectl get deployments -n codacy | awk '{print "deployment/"$1}' | tail -n +2 )
            for DEPLOYMENT in ${DEPLOYMENTS[@]}
            do
                kubectl rollout status -n codacy --timeout=30m --watch "$DEPLOYMENT"
            done
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir

  helm_push: &helm_push
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Install requirements"
          command: |
            apk add --no-cache python3
            pip3 install ytool
      - run:
          name: Set image tag and version using semver
          command: |
            ytool -s appVersion "$(cat .version)" -s version "$(cat .version)" -f "./codacy/Chart.yaml" -e
            git --no-pager diff --no-color
      - run:
          name: Push to charts museum
          command: |
            helm dep up ./codacy
            echo "Adding 'https://charts.codacy.com/${CHANNEL}'"
            helm repo add --username "${CHARTS_REPO_USER}" --password "${CHARTS_REPO_PASS}" codacy https://charts.codacy.com/${CHANNEL}
            helm push ./codacy codacy
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir

  setup_qa_environment: &setup_qa_environment
    steps:
      - <<: *doctl_authenticate
      - run:
          name: Install selenium
          command: |
            doctl kubernetes cluster kubeconfig save "$DOKS_CLUSTER_NAME" --set-current-context
            helm repo add stable https://kubernetes-charts.storage.googleapis.com
            helm install --name=selenium --namespace=$NAMESPACE stable/selenium

  qa_job: &qa_job
    steps:
      - <<: *doctl_authenticate
      - run:
          name: Run tests
          command: |
            export EXECUTION_TIME=`date +%F_%Hh%M-%Z`
            sh /opt/tests/qa-automation-test-runner/build/run_tests.sh

  set_docker_credentials: &set_docker_credentials
    steps:
      - <<: *doctl_authenticate
      - run:
          name: Set cluster
          command: doctl kubernetes cluster kubeconfig save "$DOKS_CLUSTER_NAME" --set-current-context
      - run:
          name: "Set Docker Credentials"
          command: kubectl create secret docker-registry docker-credentials --docker-username=$DOCKER_USERNAME --docker-password=$DOCKER_PASSWORD --namespace $NAMESPACE

jobs:
  deploy_to_doks:
    <<: *default_doks_image
    environment:
      <<: *dev_environment
    <<: *deploy_to_cluster

  deploy_to_doks_nightly:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment
    <<: *deploy_to_cluster

  purge_doks_nightly_codacy:
    environment:
      <<: *nightly_environment
    <<: *purge_cluster

  validate_deployment_status_nightly:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment
    <<: *validate_deployment_status_on_cluster

  deploy_to_doks_release:
    <<: *default_doks_image
    environment:
      <<: *release_environment
    <<: *deploy_to_cluster
  
  purge_doks_release_codacy:
    environment:
      <<: *release_environment
    <<: *purge_cluster

  validate_deployment_status_release:
    <<: *default_doks_image
    environment:
      <<: *release_environment
    <<: *validate_deployment_status_on_cluster

  helm_push_incubator:
    <<: *default_doks_image
    environment:
      <<: *incubator_helm_channel
    <<: *helm_push

  helm_push_unstable:
    <<: *default_doks_image
    environment:
      <<: *unstable_helm_channel
    <<: *helm_push

  update_versions:
    docker:
      - image: codacy/ci-do:0.2.3
    working_directory: ~/workdir/
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: "Store old requirements.lock"
          command: cp codacy/requirements.lock codacy/requirements_old.lock
      - run:
          name: "Get latest chart versions"
          command: make update_dependencies
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir

  get_changelogs:
    docker:
      - image: codacy/ci-base:1.0.1
    working_directory: ~/workdir/
    steps:
      - add_ssh_keys:
          fingerprints:
            - "df:83:d7:c7:d5:79:06:c2:3b:d1:fd:e2:a3:d1:12:c5"
      - attach_workspace:
          at: ~/
      - run:
          name: "Install requirements"
          command: apk add sudo util-linux && curl -Lo /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_amd64" && chmod +x /usr/local/bin/yq
      - run:
          name: "Get changelogs"
          command: bash ./.circleci/getChangelogs.sh
      - persist_to_workspace:
          root: ~/
          paths:
            - workdir
      - store_artifacts:
          path: ~/workdir/changelogs

  set_docker_credentials_nightly:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment
    <<: *set_docker_credentials

  set_docker_credentials_release:
    <<: *default_doks_image
    environment:
      <<: *release_environment
    <<: *set_docker_credentials

  setup_qa_environment_nightly:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment
      <<: *qa_environment_nightly
    <<: *setup_qa_environment

  qa_tests_nightly:
    <<: *qa_automation_image
    environment:
      <<: *nightly_environment
      <<: *qa_environment_nightly
    <<: *qa_job
      
workflows:
  helm_lint:
    jobs:
      - codacy/checkout_and_version:
          filters:
            branches:
              ignore:
                - dev
                - master
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version

  deploy_chart_to_cluster:
    jobs:
      - codacy/checkout_and_version:
          filters:
            branches:
              only:
                - dev
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version
      - deploy_to_doks:
          context: CodacyDO
          requires:
            - helm_lint
      - helm_push_unstable:
          context: CodacyDO
          requires:
            - deploy_to_doks

  nightly_pipeline:
    triggers:
       - schedule:
           cron: "0 0 * * 1-5"
           filters:
             branches:
               only:
                 - dev
    jobs:
      - codacy/checkout_and_version
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version
      - purge_doks_nightly_codacy:
          context: CodacyDO
          requires:
            - helm_lint
      - set_docker_credentials_nightly:
          context: CodacyDO
          requires:
            - purge_doks_nightly_codacy
      - update_versions:
          context: CodacyDO
          requires:
            - set_docker_credentials_nightly
      - get_changelogs:
          context: CodacyDO
          requires:
            - update_versions
      - deploy_to_doks_nightly:
          context: CodacyDO
          requires:
            - codacy/checkout_and_version
            - purge_doks_nightly_codacy
            - update_versions
            - get_changelogs
      - helm_push_unstable:
          context: CodacyDO
          requires:
            - deploy_to_doks_nightly
      - validate_deployment_status_nightly:
          context: CodacyDO
          requires:
            - deploy_to_doks_nightly
      - qa_tests_nightly:
          context: CodacyDO
          requires:
            - validate_deployment_status_nightly
      - codacy/helm_promote:
          name: promote_chart_to_stable
          context: CodacyHelm
          chart_name: codacy
          source_charts_repo_url: "https://charts.codacy.com/unstable"
          target_charts_repo_url: "https://charts.codacy.com/nightly"
          requires:
            - validate_deployment_status_nightly

  release_pipeline:
    jobs:
      - codacy/checkout_and_version:
          filters:
             branches:
               only:
                 - master
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version
      - purge_doks_release_codacy:
          context: CodacyDO
          requires:
            - helm_lint
      - set_docker_credentials_release:
          context: CodacyDO
          requires:
            - purge_doks_release_codacy
      - update_versions:
          context: CodacyDO
          requires:
            - set_docker_credentials_release
      - get_changelogs:
          context: CodacyDO
          requires:
            - update_versions
      - deploy_to_doks_release:
          context: CodacyDO
          requires:
            - codacy/checkout_and_version
            - purge_doks_release_codacy
            - update_versions
            - get_changelogs
      - validate_deployment_status_release:
          context: CodacyDO
          requires:
            - deploy_to_doks_release
      - helm_push_incubator:
          context: CodacyDO
          requires:
            - validate_deployment_status_release
      - manual_qa_hold:
          type: approval
          context: CodacyDO
          requires:
           - helm_push_incubator
      - codacy/tag_version:
          name: tag_version
          context: CodacyDO
          requires:
            - manual_qa_hold
      - codacy/helm_promote:
          name: promote_chart_to_stable
          context: CodacyHelm
          chart_name: codacy
          source_charts_repo_url: "https://charts.codacy.com/incubator"
          target_charts_repo_url: "https://charts.codacy.com/stable"
          requires:
            - tag_version
