version: 2.1

orbs:
  codacy: codacy/base@1.2.1

references:
  default_doks_image: &default_doks_image
    docker:
      - image: codacy/ci-do:0.2.3
    working_directory: ~/workdir/

  qa_automation_image: &qa_automation_image
    docker:
      - image: codacy/qa-automation-test-runner:1.3.0
      - image: selenium/standalone-chrome:3.141.0
        environment:
          JAVA_OPTS: -Xss256m -Xmx512m
          MAVEN_OPTS: -showversion -Xms256m -Xmx512m
    working_directory: ~/workdir

  # doks node types can be found here https://developers.digitalocean.com/documentation/v2/
  dev_environment: &dev_environment
    DOKS_CLUSTER_NAME: codacy-doks-cluster-dev
    DO_TF_WORKSPACE: dev
    RELEASE_NAME: codacy
    NAMESPACE: codacy
    NODE_TYPE: s-20vcpu-96gb
    K8S_VERSION: 1.14
    NUM_NODES: 5
    HELM_REPOSITORY: codacy-unstable

  nightly_base_environment: &nightly_base_environment
    RELEASE_NAME: codacy-nightly
    NAMESPACE: codacy-nightly
    NODE_TYPE: s-20vcpu-96gb
    NUM_NODES: 4
    HELM_REPOSITORY: codacy-unstable

  nightly_environment_1_14: &nightly_environment_1_14
    <<: *nightly_base_environment
    DO_TF_WORKSPACE: nightly-1-14
    DOKS_CLUSTER_NAME: codacy-doks-cluster-nightly-1-14
    K8S_VERSION: 1.14

  nightly_environment_1_15: &nightly_environment_1_15
    <<: *nightly_base_environment
    DO_TF_WORKSPACE: nightly-1-15
    DOKS_CLUSTER_NAME: codacy-doks-cluster-nightly-1-15
    K8S_VERSION: 1.15

  release_environment: &release_environment
    DOKS_CLUSTER_NAME: codacy-doks-cluster-release
    DO_TF_WORKSPACE: release
    RELEASE_NAME: codacy-release
    NAMESPACE: codacy-release
    NODE_TYPE: s-20vcpu-96gb
    K8S_VERSION: 1.15
    NUM_NODES: 4
    CODACY_URL: http://release.dev.codacy.org
    HELM_REPOSITORY: codacy-incubator

  qa_environment_hourly: &qa_environment_hourly
    SELENIUM_DRIVER_URL: http://localhost:4444/wd/hub
    HUB_URL: http://localhost:4444/wd/hub
    PROJECT_NAME: codacy-chart
    TEST_PATH: Suite/Enterprise/WEB_DEV.xml
    LAUNCH_NAME: ENTERPRISE_WEB_DEV_DOKS
    LAUNCH_DESCRIPTION: 'Automated Tests Ran by CircleCI'
    LAUNCH_TAG: CIRCLECI;WEB;DIGITALOCEAN;ENTERPRISE
    RP_ENDPOINT: https://reportportal.staging.codacy.org
    DOKS_CLUSTER_NAME: codacy-doks-cluster-dev
    DO_TF_WORKSPACE: dev
    RELEASE_NAME: codacy-hourly
    NAMESPACE: codacy-hourly
    NODE_TYPE: s-20vcpu-96gb
    K8S_VERSION: 1.14
    NUM_NODES: 5
    HELM_REPOSITORY: codacy-unstable

  unstable_helm_channel: &unstable_helm_channel
    CHANNEL: unstable
    HELM_REPOSITORY: codacy-unstable

  incubator_helm_channel: &incubator_helm_channel
    CHANNEL: incubator
    HELM_REPOSITORY: codacy-incubator

  nightly_helm_channel: &nightly_helm_channel
    CHANNEL: nightly
    HELM_REPOSITORY: codacy-nightly

  stable_helm_channel: &stable_helm_channel
    CHANNEL: stable
    HELM_REPOSITORY: codacy-stable

  doctl_authenticate: &doctl_authenticate
    run:
      name: "Setup DO Credentials"
      command: doctl auth init -t $DO_TOKEN &>/dev/null

  persist_to_workspace: &persist_to_workspace
    persist_to_workspace:
        root: ~/
        paths:
          - workdir

  attach_workspace: &attach_workspace
    attach_workspace:
          at: ~/

  helm_lint: &helm_lint
    run:
          name: "Helm lint"
          command: helm lint codacy/

  deploy_to_cluster: &deploy_to_cluster
    steps:
      - <<: *attach_workspace
      - <<: *helm_lint
      - <<: *doctl_authenticate
      - deploy:
          name: Install Codacy
          command: make -C .doks/ deploy_to_doks RELEASE=$RELEASE NAMESPACE=$NAMESPACE

  deploy_to_cluster_from_chartmuseum: &deploy_to_cluster_from_chartmuseum
    steps:
      - <<: *attach_workspace
      - <<: *helm_lint
      - <<: *doctl_authenticate
      - deploy:
          name: Install Codacy
          command: make -C .doks/ deploy_to_doks_from_chartmuseum RELEASE=$RELEASE NAMESPACE=$NAMESPACE VERSION=$(cat .version) HELM_REPOSITORY=$HELM_REPOSITORY


  validate_deployment_status_on_cluster: &validate_deployment_status_on_cluster
    steps:
      - <<: *attach_workspace
      - <<: *doctl_authenticate
      - run:
          name: "Validate deployment status"
          command: |
            set -e
            doctl kubernetes cluster kubeconfig save "$DOKS_CLUSTER_NAME" --set-current-context
            DEPLOYMENTS=$(kubectl get deployments -n "$NAMESPACE" | awk '{print "deployment/"$1}' | tail -n +2 )
            for DEPLOYMENT in ${DEPLOYMENTS[@]}
            do
                kubectl rollout status -n "$NAMESPACE" --timeout=30m --watch "$DEPLOYMENT"
            done

  helm_push: &helm_push
    steps:
      - <<: *attach_workspace
      - run:
          name: "Install requirements"
          command: |
            apk add --no-cache python3
            pip3 install ytool
      - run:
          name: Set image tag and version using semver
          command: |
            ytool -s appVersion "$(cat .version)" -s version "$(cat .version)" -f "./codacy/Chart.yaml" -e
            git --no-pager diff --no-color
      - run:
          name: Push to charts museum
          command: |
            helm dep up ./codacy
            echo "Adding 'https://charts.codacy.com/${CHANNEL}'"
            helm repo add --username "${CHARTS_REPO_USER}" --password "${CHARTS_REPO_PASS}" ${HELM_REPOSITORY} https://charts.codacy.com/${CHANNEL}
            helm push ./codacy ${HELM_REPOSITORY}
      - <<: *persist_to_workspace

  qa_job: &qa_job
    steps:
      - <<: *attach_workspace
      - deploy:
          name: Run tests
          command: |
            export EXECUTION_TIME=`date +%F_%Hh%M-%Z`
            source .apiurl
            export URL=http://$CODACY_API
            export URLLANDING=$URL/
            export URLLOGGED=$URL/projects
            sh /opt/tests/qa-automation-test-runner/build/run_tests.sh

  update_codacy_url: &update_codacy_url
    steps:
      - checkout
      - <<: *doctl_authenticate
      - run:
          name: Set cluster
          command: doctl kubernetes cluster kubeconfig save "$DOKS_CLUSTER_NAME" --set-current-context
      - deploy:
          name: Wait for codacy-api ingress
          command: |
            external_ip=""; while [ -z $external_ip ]; do echo "Waiting for codacy-api ingress..."; external_ip=$(kubectl get service -n "$NAMESPACE" codacy-api --template="{{range .status.loadBalancer.ingress}}{{.ip}}{{end}}"); [ -z "$external_ip" ] && sleep 10; done; echo "End point ready-" && echo $external_ip; export endpoint=$external_ip
            echo "CODACY_API=$endpoint" > .apiurl
      - deploy:
          name: Update codacy-api ip address
          command: |
              CODACY_HOSTNAME=$(kubectl get services codacy-api --namespace $NAMESPACE -o=jsonpath='{.status.loadBalancer.ingress[0].ip}');
              make -C .doks/ deploy_to_doks RELEASE=$RELEASE NAMESPACE=$NAMESPACE CODACY_URL=http://$CODACY_HOSTNAME

jobs:
  deploy_to_doks:
    <<: *default_doks_image
    environment:
      <<: *dev_environment
    <<: *deploy_to_cluster

  deploy_to_doks_hourly:
    <<: *default_doks_image
    environment:
      <<: *qa_environment_hourly
    <<: *deploy_to_cluster_from_chartmuseum

  deploy_to_doks_nightly_1_14:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment_1_14
    <<: *deploy_to_cluster_from_chartmuseum

  deploy_to_doks_nightly_1_15:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment_1_15
    <<: *deploy_to_cluster_from_chartmuseum

  validate_deployment_status_hourly:
    <<: *default_doks_image
    environment:
      <<: *dev_environment
    <<: *validate_deployment_status_on_cluster

  validate_deployment_status_nightly_1_14:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment_1_14
    <<: *validate_deployment_status_on_cluster

  validate_deployment_status_nightly_1_15:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment_1_15
    <<: *validate_deployment_status_on_cluster

  deploy_to_doks_release:
    <<: *default_doks_image
    environment:
      <<: *release_environment
    <<: *deploy_to_cluster_from_chartmuseum

  validate_deployment_status_release:
    <<: *default_doks_image
    environment:
      <<: *release_environment
    <<: *validate_deployment_status_on_cluster

  helm_push_incubator:
    <<: *default_doks_image
    environment:
      <<: *incubator_helm_channel
    <<: *helm_push

  helm_push_unstable:
    <<: *default_doks_image
    environment:
      <<: *unstable_helm_channel
    <<: *helm_push

  update_codacy_url_nightly_1_14:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment_1_14
    <<: *update_codacy_url

  update_codacy_url_nightly_1_15:
    <<: *default_doks_image
    environment:
      <<: *nightly_environment_1_15
    <<: *update_codacy_url

  qa_tests_hourly:
    <<: *qa_automation_image
    environment:
      <<: *dev_environment
      <<: *qa_environment_hourly
    <<: *qa_job

  set_chart_version_nightly:
    <<: *default_doks_image
    steps:
      - <<: *attach_workspace
      - run:
          name: Set chart version suffix
          command: |
            sed -E 's/(codacy-[0-9]+\.[0-9]+\.[0-9]+)-(.*)\.(.*)/\1-NIGHTLY.\3/g' .version
      - <<: *persist_to_workspace

  update_versions:
    docker:
      - image: codacy/ci-do:0.2.3
    working_directory: ~/workdir/
    steps:
      - <<: *attach_workspace
      - run:
          name: "Get latest chart versions"
          command: make update_dependencies
      - <<: *persist_to_workspace

  upload_docs:
    docker:
      - image: circleci/python:3.8
    working_directory: ~/workdir/
    steps:
      - <<: *attach_workspace
      - add_ssh_keys:
          fingerprints:
            - "df:83:d7:c7:d5:79:06:c2:3b:d1:fd:e2:a3:d1:12:c5"
      - run:
          name: ssh keyscan
          command: |
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: Set cluster
          command: |
            sudo pip install -r requirements.pip
            mkdocs gh-deploy

  get_changelogs:
    docker:
      - image: codacy/ci-base:1.0.1
    working_directory: ~/workdir/
    steps:
      - add_ssh_keys:
          fingerprints:
            - "df:83:d7:c7:d5:79:06:c2:3b:d1:fd:e2:a3:d1:12:c5"
      - <<: *attach_workspace
      - run:
          name: "Install requirements"
          command: apk add sudo util-linux && curl -Lo /usr/local/bin/yq "https://github.com/mikefarah/yq/releases/download/2.4.0/yq_linux_amd64" && chmod +x /usr/local/bin/yq
      - run:
          name: setup ssh
          command: |
            ssh-keyscan bitbucket.org >> ~/.ssh/known_hosts
            ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: "Get changelogs"
          command: bash ./.circleci/getChangelogs.sh
      - <<: *persist_to_workspace
      - store_artifacts:
          path: ~/workdir/changelogs

workflows:
  helm_lint:
    jobs:
      - codacy/checkout_and_version:
          filters:
            branches:
              ignore:
                - master
                - release
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version

  deploy_chart_to_cluster:
    jobs:
      - codacy/checkout_and_version:
          dev_branch: "master"
          release_branch: "release"
          filters:
            branches:
              only:
                - master
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version
      - helm_push_unstable:
          context: CodacyDO
          requires:
            - deploy_to_doks
      - deploy_to_doks:
          context: CodacyDO
          requires:
            - helm_lint
      - upload_docs:
          requires:
            - deploy_to_doks

  hourly_pipeline:
    # triggers:
    #     - schedule:
    #         cron: "* 0 * * 1-5"
    #         filters:
    #           branches:
    #             only:
    #               - master
    jobs:
      - codacy/checkout_and_version:
          dev_branch: "master"
          release_branch: "release"
          filters:
              branches:
                only:
                  - feature/hourly_tests
      - update_versions:
          context: CodacyDO
          requires:
            - helm_lint
      - helm_push_unstable:
          context: CodacyDO
          requires:
            - update_versions
      - get_changelogs:
          context: CodacyDO
          requires:
            - update_versions
      - deploy_to_doks_hourly:
          context: CodacyDO
          requires:
            - helm_push_unstable
      - validate_deployment_status_hourly:
          context: CodacyDO
          requires:
            - get_changelogs
      - qa_tests_hourly:
          context: CodacyDO
          requires:
            - validate_deployment_status_hourly

  nightly_pipeline:
    # triggers:
    #    - schedule:
    #        cron: "0 0 * * 1-5"
    #        filters:
    #          branches:
    #            only:
    #              - master
    jobs:
      - codacy/checkout_and_version:
          dev_branch: "master"
          release_branch: "release"
          filters:
             branches:
               only:
                 - feature/multiple_nightly
      - set_chart_version_nightly:
          context: CodacyDO
          requires:
            - codacy/checkout_and_version
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - set_chart_version_nightly
      - update_versions:
          context: CodacyDO
          requires:
            - helm_lint
      - helm_push_unstable:
          context: CodacyDO
          requires:
            - update_versions
      - get_changelogs:
          context: CodacyDO
          requires:
            - update_versions
      - deploy_to_doks_nightly_1_14:
          context: CodacyDO
          requires:
            - helm_push_unstable
      - validate_deployment_status_nightly_1_14:
          context: CodacyDO
          requires:
            - deploy_to_doks_nightly_1_14
      - update_codacy_url_nightly_1_14:
          context: CodacyDO
          requires:
            - validate_deployment_status_nightly_1_14
      - deploy_to_doks_nightly_1_15:
          context: CodacyDO
          requires:
            - helm_push_unstable
      - validate_deployment_status_nightly_1_15:
          context: CodacyDO
          requires:
            - deploy_to_doks_nightly_1_15
      - update_codacy_url_nightly_1_15:
          context: CodacyDO
          requires:
            - validate_deployment_status_nightly_1_15
      - codacy/helm_promote:
          name: promote_chart_to_stable
          context: CodacyHelm
          chart_name: codacy
          source_charts_repo_url: "https://charts.codacy.com/unstable"
          target_charts_repo_url: "https://charts.codacy.com/nightly"
          requires:
            - update_codacy_url_nightly_1_14
            - update_codacy_url_nightly_1_15

  release_pipeline:
    jobs:
      - codacy/checkout_and_version:
          dev_branch: "master"
          release_branch: "release"
          filters:
             branches:
               only:
                 - release
      - codacy/helm_aws:
          name: helm_lint
          cmd: helm lint codacy/
          requires:
            - codacy/checkout_and_version
      - helm_push_incubator:
          context: CodacyDO
          requires:
            - helm_lint
      - get_changelogs:
          context: CodacyDO
          requires:
            - helm_push_incubator
      - deploy_to_doks_release:
          context: CodacyDO
          requires:
            - helm_push_incubator
      - validate_deployment_status_release:
          context: CodacyDO
          requires:
            - deploy_to_doks_release
      - manual_qa_hold:
          type: approval
          context: CodacyDO
          requires:
           - validate_deployment_status_release
      - codacy/tag_version:
          name: tag_version
          context: CodacyDO
          requires:
            - manual_qa_hold
      - codacy/helm_promote:
          name: promote_chart_to_stable
          context: CodacyHelm
          chart_name: codacy
          source_charts_repo_url: "https://charts.codacy.com/incubator"
          target_charts_repo_url: "https://charts.codacy.com/stable"
          requires:
            - tag_version
