apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-load-definition
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  load_definition.json: |-
    {
      "queues": [
        {
            "arguments": {},
            "auto_delete": false,
            "durable": true,
            "name": "codacy-engine",
            "type": "classic",
            "vhost": "/"
        },
        {
            "arguments": {},
            "auto_delete": false,
            "durable": true,
            "name": "portal",
            "type": "classic",
            "vhost": "/"
        },
        {
            "arguments": {},
            "auto_delete": false,
            "durable": true,
            "name": "crow",
            "type": "classic",
            "vhost": "/"
        },
        {
            "arguments": {},
            "auto_delete": false,
            "durable": true,
            "name": "listener",
            "type": "classic",
            "vhost": "/"
        }
      ]
    }