{{ if .Values.fluentdoperator.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.fluentdoperator.defaultConfigmap }}
  labels:
    {{- include "codacy.labels" . | indent 4 }}
data:
  fluent.conf: |
    <filter **>
      @type record_modifier
      <record>
        # This removes unneeded fields from the logs
        for_remove ${record["kubernetes"].delete("namespace_name"); record["kubernetes"].delete("pod_id"); record["kubernetes"].delete("namespace_labels"); record["kubernetes"].delete("container_info"); record["kubernetes"].delete("labels"); record.delete("container_info"); record.delete("docker")}
      </record>
      remove_keys for_remove
    </filter>


    <match **>
      # docs: https://docs.fluentd.org/output/s3
      @type s3
      @id out_s3
      @log_level info

      aws_key_id {{ .Values.global.minio.accessKey }}
      aws_sec_key {{ .Values.global.minio.secretKey }}

      s3_endpoint http://{{ .Values.global.minio.location }}:9000
      s3_bucket fluentd-bucket # The bucket is created automatically
      s3_region eu-west-1
      force_path_style true # This prevents AWS SDK from breaking endpoint URL

      s3_object_key_format %{path}%Y/%m/%d/cluster-log-%{index}.%{file_extension}

      <format>
        @type json
      </format>

      <buffer>
        @type file
        path /var/log/fluentd-buffers/s3.buffer
        timekey 600 # Time frames of 10 minutes
        timekey_wait 0 # We want to send the logs from the timeframe to s3 as soon as possible
        timekey_use_utc true
        chunk_limit_size 256m
      </buffer>
    </match>
{{ end }}