grafana:
  enabled: true
  #adminPassword: <--- admin user password --->
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
  #  hosts: <--- grafana url --->
  sidecar:
    dashboards:
      searchNamespace: ALL
    datasources:
      defaultDatasourceEnabled: false
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki:3100
      version: 1
      orgId: 1
      access: proxy
      basicAuth: false
      editable: true
      jsonData:
         tlsSkipVerify: true
    - name: Prometheus
      type: prometheus
      url: http://monitoring-prometheus-oper-prometheus:9090
      version: 1
      orgId: 1
      access: proxy
      basicAuth: false
      editable: true
      jsonData:
         tlsSkipVerify: true

prometheusOperator:
  createCustomResource: false
  tlsProxy:
    enabled: false
  admissionWebhooks:
    enabled: false
    patch:
      enabled: false
    tlsProxy:
      enabled: false

prometheus:
  ingressPerReplica:
    tlsSecretPerReplica:
      enabled: false
  thanos:
    service:
      enabled: false
  service:
    sessionAffinity: "ClientIP"
  prometheusSpec:
    replicas: 1
    serviceMonitorSelectorNilUsesHelmValues: false
    walCompression: true

additionalPrometheusRulesMap:
  - groups:
      # From: https://awesome-prometheus-alerts.grep.to/rules#rabbitmq
      - name: rabbitmq-alert-rules
        rules:
          - alert: RabbitmqDown
            expr: rabbitmq_up == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq down (instance {{ $labels.instance }})"
              description: "RabbitMQ node down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels.instance }}"
          - alert: RabbitmqClusterDown
            expr: sum(rabbitmq_running) < 1  # This value should change depending on the replicaCount of rabbitmq-ha
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq cluster down (instance {{ $labels.instance }})"
              description: "Less than 1 node(s) running in RabbitMQ cluster\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqDeadLetterQueueFillingUp
            expr: rabbitmq_queue_messages{queue="my-dead-letter-queue"} > 10
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq dead letter queue filling up (instance {{ $labels.instance }})"
              description: "Dead letter queue is filling up (> 10 msgs)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqClusterPartition
            expr: rabbitmq_partitions > 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq cluster partition (instance {{ $labels.instance }})"
              description: "Cluster partition\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqOutOfMemory
            expr: rabbitmq_node_mem_used / rabbitmq_node_mem_limit * 100 > 90
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Rabbitmq out of memory (instance {{ $labels.instance }})"
              description: "Memory available for RabbmitMQ is low (< 10%)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqTooManyConnections
            expr: rabbitmq_connectionsTotal > 1000
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Rabbitmq too many connections (instance {{ $labels.instance }})"
              description: "RabbitMQ instance has too many connections (> 1000)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqDeadLetterQueueFillingUp
            expr: rabbitmq_queue_messages{queue="my-dead-letter-queue"} > 10
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq dead letter queue filling up (instance {{ $labels.instance }})"
              description: "Dead letter queue is filling up (> 10 msgs)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqTooManyMessagesInQueue
            expr: rabbitmq_queue_messages_ready{queue="my-queue"} > 1000
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Rabbitmq too many messages in queue (instance {{ $labels.instance }})"
              description: "Queue is filling up (> 1000 msgs)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqSlowQueueConsuming
            expr: time() - rabbitmq_queue_head_message_timestamp{queue="my-queue"} > 60
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Rabbitmq slow queue consuming (instance {{ $labels.instance }})"
              description: "Queue messages are consumed slowly (> 60s)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqNoConsumer
            expr: rabbitmq_queue_consumers == 0
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq no consumer (instance {{ $labels.instance }})"
              description: "Queue has no consumer\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqTooManyConsumers
            expr: rabbitmq_queue_consumers > 1
            for: 5m
            labels:
              severity: critical
            annotations:
              summary: "Rabbitmq too many consumers (instance {{ $labels.instance }})"
              description: "Queue should have only 1 consumer\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
          - alert: RabbitmqUnactiveExchange
            expr: rate(rabbitmq_exchange_messages_published_in_total{exchange="my-exchange"}[1m]) < 5
            for: 5m
            labels:
              severity: warning
            annotations:
              summary: "Rabbitmq unactive exchange (instance {{ $labels.instance }})"
              description: "Exchange receive less than 5 msgs per second\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"