codacy-api:
  replicaCount: 2
  service:
    type: ClusterIP
    port: 80

postgres:
  persistence:
    enabled: true
    size: 1000Gi

portal:
  replicaCount: 1

activities:
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5
  activitiesdb:
    persistence:
      enabled: true
      size: 250Gi

remote-provider-service:
  replicaCount: 1

hotspots-api:
  replicaCount: 1
  hotspotsdb:
    persistence:
      enabled: true
      size: 250Gi

hotspots-worker:
  replicaCount: 1

listener:
  replicaCount: 1
  listenerdb:
    persistence:
      enabled: true
      size: 250Gi

  persistence:
    claim:
      size: 140Gi

  nfsserverprovisioner:
    enabled: true
    persistence:
      enabled: true
      size: 200Gi

core:
  replicaCount: 1

engine:
  replicaCount: 1

worker-manager:
  replicaCount: 1
  config:
    workers:
      genericMax: 20
      dedicatedMax: 20

fluentdoperator:
  enabled: true

global:
  githubEnterprise:
    enabled: "true"
    hostname: "github.dev.codacy.org"
    port: 443
    protocol: "https"
    disableSSL: "true"
    isPrivateMode: "true"

  gitlabEnterprise:
    enabled: "true"
    hostname: "gitlab.dev.codacy.org"
    protocol: "http"
    port: 80

  bitbucketEnterprise:
    enabled: "true"
    hostname: "bitbucket-server.codacy.org"
    protocol: "http"
    port: 7990
    consumerKey: "codacy-stash-link"

codacy-ingress:
  create: true
  ingress:
    hostname:
      app: <codacy-app.dns.internal>
      api: <codacy-api.dns.internal>
    annotations:
      kubernetes.io/ingress.class: nginx
      certmanager.k8s.io/acme-challenge-type: http01
      certmanager.k8s.io/cluster-issuer: letsencrypt
      external-dns.alpha.kubernetes.io/hostname: <codacy-app.dns.internal>, <codacy-api.dns.internal>
      external-dns.alpha.kubernetes.io/scope: public
      nginx.ingress.kubernetes.io/proxy-body-size: 128m
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/use-regex: "true"
    extraPaths:
      - backend:
          serviceName: codacy-crow
          servicePort: http
        path: /monitoring