global:
  defaultdb:
    create: true

  analysisdb:
    create: true

  resultsdb:
    create: true

  metricsdb:
    create: true

  filestoredb:
    create: true

  jobsdb:
    create: true

  github:
    enabled: "true"
    login: "false"

  githubEnterprise:
    enabled: "true"
    login: "true"
    hostname: "github.dev.codacy.org"
    port: 443
    protocol: "https"
    disableSSL: "true"
    isPrivateMode: "true"

  gitlab:
    enabled: "true"
    login: "false"

  gitlabEnterprise:
    enabled: "true"
    login: "true"
    hostname: "gitlab.dev.codacy.org"
    protocol: "http"
    port: 80

  bitbucket:
    enabled: "true"
    login: "false"

  bitbucketEnterprise:
    enabled: "true"
    login: "true"
    hostname: "bitbucket-server.codacy.org"
    protocol: "http"
    port: 7990

codacy-ingress:
  create: true
  ingress:
    hostname:
      app: <codacy-app.dns.internal>
      api: <codacy-api.dns.internal>
    spa:
      serviceName: codacy-spa # this will be moved to the ingress default configs when the spa is released

codacy-api:
  replicaCount: 2
  service:
    type: ClusterIP

postgres:
  persistence:
    enabled: true
    size: 1000Gi

portal:
  replicaCount: 1

activities:
  replicaCount: 1
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 3
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 5
    failureThreshold: 5
  activitiesdb:
    create: true
    persistence:
      enabled: true
      size: 250Gi

remote-provider-service:
  replicaCount: 1

hotspots-api:
  replicaCount: 1
  hotspotsdb:
    create: true
    persistence:
      enabled: true
      size: 250Gi

hotspots-worker:
  replicaCount: 1

listener:
  replicaCount: 1
  listenerdb:
    create: true
    persistence:
      enabled: true
      size: 250Gi

  persistence:
    claim:
      size: 140Gi

  nfsserverprovisioner:
    enabled: true
    persistence:
      enabled: true
      size: 200Gi

core:
  replicaCount: 1

engine:
  replicaCount: 1

worker-manager:
  replicaCount: 1
  config:
    workers:
      dedicatedMax: 20

fluentdoperator:
  enabled: true

crow:
  replicaCount: 1
  fullnameOverride: codacy-crow
  crowdb:
    create: true
    host: codacy-crowdb
    postgresqlUsername: "codacy"
    postgresqlDatabase: "crow"
    postgresqlPassword: "PLEASE_CHANGE_ME"
    service:
      port: 5432
    fullnameOverride: codacy-crowdb
  config:
    play:
      http:
        context: "/monitoring"
    passwordAuth:
      password: "PLEASE_CHANGE_ME"

