dependencies:
- name: minio
  version: 5.0.33
  repository: https://charts.helm.sh/stable
  condition: global.minio.create
  alias: minio

- name: rabbitmq
  version: 3.8.5
  repository: https://raw.githubusercontent.com/bitnami/charts/archive-full-index/bitnami
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

  # Github tag before bitnami truncated the index. Old link didn't work anymore
- name: postgresql
  version: 8.6.4
  repository: https://raw.githubusercontent.com/bitnami/charts/defb094c658024e4aa8245622dab202874880cbc/bitnami
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb.create,
    global.metricsdb.create, global.filestoredb.create, global.jobsdb.create

- name: log-router
  version: 0.6.4
  repository: https://charts.codacy.com/external
  condition: fluentdoperator.enabled
  alias: fluentdoperator
  git: git@github.com:codacy/kube-fluentd-operator.git

- name: codacy-ingress-sh
  alias: codacy-ingress
  version: ">=0.1.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/codacy-ingress-sh.git
  condition: codacy-ingress.create

- name: portal-sh
  alias: portal
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/portal-sh.git
  condition: portal.create

- name: ragnaros-sh
  alias: ragnaros
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/ragnaros-sh.git
  condition: ragnaros.create

- name: remote-provider-service-sh
  alias: remote-provider-service
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/remote-provider-service-sh.git
  condition: remote-provider-service.create

- name: listener-sh
  alias: listener
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/repository-listener-sh.git
  condition: listener.create

- name: engine-sh
  alias: engine
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/codacy-worker-sh.git
  condition: engine.create

- name: codacy-tools-sh
  alias: codacy-tools
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/codacy-tools-sh.git
  condition: codacy-tools.create

- name: codacy-api-sh
  alias: codacy-api
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/codacy-website-sh.git
  condition: codacy-api.create

- name: worker-manager-sh
  alias: worker-manager
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/worker-manager-sh.git
  condition: worker-manager.create

- name: crow-sh
  alias: crow
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/crow-sh.git
  condition: crow.create

- name: codacy-spa-sh
  alias: codacy-spa
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy-sh/codacy-spa-sh.git
  condition: codacy-spa.create
