dependencies:
- name: minio
  version: ~2.4.18
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.minio.create
  alias: minio

- name: rabbitmq-ha
  version: ~1.27.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

- name: postgresql
  version: ~4.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb201709.create, global.resultsdb.create, global.metricsdb.create, global.filestoredb.create, global.jobsdb.create, global.jobsdb.create

- name: portal
  version: ~4.25.6
  repository: https://charts.codacy.com/stable

- name: ragnaros
  version: ~14.7.2
  repository: https://charts.codacy.com/stable

- name: activities
  version: ~1.0.173
  repository: https://charts.codacy.com/stable

- name: remote-provider-service
  version: ~2.28.4
  repository: https://charts.codacy.com/stable

- name: hotspots-api
  version: ~1.2.3
  repository: https://charts.codacy.com/stable

- name: hotspots-worker
  version: ~1.2.3
  repository: https://charts.codacy.com/stable

- name: listener
  version: ~7.1.3
  repository: https://charts.codacy.com/stable

- name: core
  version: ~2.8.2
  repository: https://charts.codacy.com/stable

- name: engine
  version: ~5.42.3
  repository: https://charts.codacy.com/stable

- name: codacy-api
  version: ~4.79.0
  repository: https://charts.codacy.com/stable