dependencies:
- name: minio
  version: 2.5.18
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.minio.create
  alias: minio

- name: rabbitmq-ha
  version: 1.44.3
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

- name: postgresql
  version: 4.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb.create,
    global.metricsdb.create, global.filestoredb.create, global.jobsdb.create

- name: log-router
  version: 0.4.1
  repository: https://charts.codacy.com/external
  condition: fluentdoperator.enabled
  alias: fluentdoperator
  git: git@github.com:codacy/kube-fluentd-operator.git

- name: codacy-ingress
  version: "0.2.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-ingress.git
  condition: codacy-ingress.create

- name: portal
  version: "6.13.5"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/portal.git

- name: ragnaros
  version: "23.3.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/ragnaros.git

- name: activities
  version: "1.4.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-activities.git

- name: remote-provider-service
  version: "8.15.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/remote-provider-service.git

- name: hotspots-api
  version: "1.4.6"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/hotspots-api.git

- name: hotspots-worker
  version: "1.5.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/hotspots-worker.git

- name: listener
  version: "7.15.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/repository-listener.git

- name: core
  version: "3.1.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-core.git

- name: engine
  version: "6.11.10"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-worker.git

- name: codacy-api
  version: "11.16.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-website.git

- name: worker-manager
  version: "9.3.3"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/worker-manager.git

- name: crow
  version: "4.9.4"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/crow.git

- name: codacy-spa
  version: "0.4.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-spa.git
