dependencies:
- name: minio
  version: 5.0.33
  repository: https://charts.helm.sh/stable
  condition: global.minio.create
  alias: minio

- name: rabbitmq
  version: 7.5.7
  repository: https://charts.bitnami.com/bitnami
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

- name: postgresql
  version: 8.6.4
  repository: https://charts.bitnami.com/bitnami
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb.create,
    global.metricsdb.create, global.filestoredb.create, global.jobsdb.create

- name: log-router
  version: 0.6.3
  repository: https://charts.codacy.com/external
  condition: fluentdoperator.enabled
  alias: fluentdoperator
  git: git@github.com:codacy/kube-fluentd-operator.git

- name: codacy-ingress
  version: "0.32.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-ingress.git
  condition: codacy-ingress.create

- name: portal
  version: "6.48.2"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/portal.git
  condition: portal.create

- name: ragnaros
  version: "36.3.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/ragnaros.git
  condition: ragnaros.create

- name: remote-provider-service
  version: "10.6.0"
  repository: https://charts.codacy.com/incubator
  git: git@github.com:codacy/remote-provider-service.git
  condition: remote-provider-service.create

- name: listener
  version: "9.4.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/repository-listener.git
  condition: listener.create

- name: engine
  version: "12.19.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-worker.git
  condition: engine.create

- name: codacy-tools
  version: "5.5.6"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-tools.git
  condition: codacy-tools.create

- name: codacy-api
  version: "26.24.8"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-website.git
  condition: codacy-api.create

- name: worker-manager
  version: "10.17.3"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/worker-manager.git
  condition: worker-manager.create

- name: crow
  version: "5.8.1"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/crow.git
  condition: crow.create

- name: codacy-spa
  version: "1.89.1"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-spa.git
  condition: codacy-spa.create
