dependencies:
- name: minio
  version: ~2.5.18
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.minio.create
  alias: minio

- name: rabbitmq-ha
  version: ~1.27.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

- name: postgresql
  version: ~4.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb201709.create, global.resultsdb.create, global.metricsdb.create, global.filestoredb.create, global.jobsdb.create, global.jobsdb.create

- name: log-router
  version: ~0.3.0
  repository: https://charts.codacy.com/external
  condition: fluentdoperator.enabled
  alias: fluentdoperator

- name: portal
  version: 4.27.1-SNAPSHOT.43925966
  repository: https://charts.codacy.com/unstable

- name: ragnaros
  version: 14.11.1
  repository: https://charts.codacy.com/incubator

- name: activities
  version: 1.0.175-SNAPSHOT.47c18ef
  repository: https://charts.codacy.com/unstable

- name: remote-provider-service
  version: ~2.28.4
  repository: https://charts.codacy.com/stable

- name: hotspots-api
  version: 1.2.3-SNAPSHOT.a65981c
  repository: https://charts.codacy.com/unstable

- name: hotspots-worker
  version: 1.2.2-SNAPSHOT.788a878
  repository: https://charts.codacy.com/unstable

- name: listener
  version: 7.2.0-SNAPSHOT.b7db0d8c
  repository: https://charts.codacy.com/unstable

- name: core
  version: 2.10.2
  repository: https://charts.codacy.com/incubator

- name: engine
  version: 5.45.0-SNAPSHOT.c4621ed1c
  repository: https://charts.codacy.com/unstable

- name: codacy-api
  version: 4.89.1-SNAPSHOT.e6cc16fce
  repository: https://charts.codacy.com/unstable

- name: worker-manager
  version: 8.0.0-releasekubernetesdev.dd8719d4
  repository: https://charts.codacy.com/unstable

- name: crow
  version: 4.3.0
  repository: https://charts.codacy.com/incubator
