dependencies:
- name: minio
  version: 2.5.18
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.minio.create
  alias: minio

- name: rabbitmq-ha
  version: 1.27.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

- name: postgresql
  version: 4.2.2
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb.create,
    global.metricsdb.create, global.filestoredb.create, global.jobsdb.create

- name: log-router
  version: 0.3.0
  repository: https://charts.codacy.com/external
  condition: fluentdoperator.enabled
  alias: fluentdoperator
  git: git@github.com:codacy/kube-fluentd-operator.git

- name: portal
  version: "6.1.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/portal.git

- name: ragnaros
  version: "19.1.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/ragnaros.git

- name: activities
  version: "1.4.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-activities.git

- name: remote-provider-service
  version: "6.1.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/remote-provider-service.git

- name: hotspots-api
  version: "1.4.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/hotspots-api.git

- name: hotspots-worker
  version: "1.4.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/hotspots-worker.git

- name: listener
  version: "7.12.1"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/repository-listener.git

- name: core
  version: "3.0.3"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-core.git

- name: engine
  version: "6.7.2"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-worker.git

- name: codacy-api
  version: "8.6.4"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/codacy-website.git

- name: worker-manager
  version: "9.1.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/worker-manager.git

- name: crow
  version: "4.5.0"
  repository: https://charts.codacy.com/stable
  git: git@bitbucket.org:qamine/crow.git
