dependencies:
- name: minio
  version: 5.0.33
  repository: https://charts.helm.sh/stable
  condition: global.minio.create
  alias: minio

- name: rabbitmq
  version: 7.5.7
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  condition: global.rabbitmq.create
  alias: rabbitmq-ha

- name: postgresql
  version: 8.6.4
  repository: https://raw.githubusercontent.com/bitnami/charts/pre-2022/bitnami
  alias: postgres
  condition: global.defaultdb.create, global.analysisdb.create, global.resultsdb.create,
    global.metricsdb.create, global.filestoredb.create, global.jobsdb.create

- name: log-router
  version: 0.6.4
  repository: https://charts.codacy.com/external
  condition: fluentdoperator.enabled
  alias: fluentdoperator
  git: git@github.com:codacy/kube-fluentd-operator.git

- name: codacy-ingress-legacy
  alias: codacy-ingress
  version: ">=0.1.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-ingress-legacy.git
  condition: codacy-ingress.create

- name: portal-legacy
  alias: portal
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/portal-legacy.git
  condition: portal.create

- name: ragnaros-legacy
  alias: ragnaros
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/ragnaros-legacy.git
  condition: ragnaros.create

- name: remote-provider-service-legacy
  alias: remote-provider-service
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/remote-provider-service-legacy.git
  condition: remote-provider-service.create

- name: listener-legacy
  alias: listener
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/repository-listener-legacy.git
  condition: listener.create

- name: engine-legacy
  alias: engine
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-worker-legacy.git
  condition: engine.create

- name: codacy-tools-legacy
  alias: codacy-tools
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-tools-legacy.git
  condition: codacy-tools.create

- name: codacy-api-legacy
  alias: codacy-api
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-website-legacy.git
  condition: codacy-api.create

- name: worker-manager-legacy
  alias: worker-manager
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/worker-manager-legacy.git
  condition: worker-manager.create

- name: crow-legacy
  alias: crow
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/crow-legacy.git
  condition: crow.create

- name: codacy-spa-legacy
  alias: codacy-spa
  version: ">=1.0.0"
  repository: https://charts.codacy.com/stable
  git: git@github.com:codacy/codacy-spa-legacy.git
  condition: codacy-spa.create
