global:
  minio:
    create: true
    location: codacy-minio.codacy.svc.cluster.local
    port: 9000

  rabbitmq:
    create: true
    rabbitmqUsername: rabbitmq
    rabbitmqPassword: rabbitmq
    rabbitmqvHost: "/"
    host: codacy-rabbitmq-ha.codacy.svc.cluster.local
    port: 5672
    ssl: false
    timeout: 15s

  defaultdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: accounts
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  analysisdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: analysis
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  resultsdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: results
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  resultsdb201709:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: results201709
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  metricsdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: metrics
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  filestoredb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: filestore
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  jobsdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: jobs
    postgresqlPassword: codacy
    host: codacy-postgres.codacy.svc.cluster.local
    service:
      port: 5432

  codacy:
    core:
      url: codacy-core.codacy.svc.cluster.local
    portal:
      url: codacy-portal.codacy.svc.cluster.local
    engine:
      url: codacy-engine.codacy.svc.cluster.local
    listener:
      url: codacy-listener.codacy.svc.cluster.local

activities:
  activitiesdb:
    create: true
    host: codacy-activitiesdb.codacy.svc.cluster.local
    postgresqlUsername: "codacy"
    postgresqlDatabase: "activities"
    postgresqlPassword: "PLEASE_CHANGE_ME"
    service:
      port: 5432

listener:
  config:
    play:
      configFile: application.enterprise.conf
      logFile: logback.xml
  listenerdb:
    create: true
    host: codacy-listenerdb.codacy.svc.cluster.local
    postgresqlUsername: "codacy"
    postgresqlDatabase: "listener"
    postgresqlPassword: "PLEASE_CHANGE_ME"
    service:
      port: 5432

engine:
  config:
    play:
      configFile: 'enterprise-engine.conf'
      logFile: 'logback.xml'
    redis:
      enable: false
    s3:
      emulator:
        location: codacy-minio.codacy.svc.cluster.local
        port: 9000

hotspots-api:
  hotspotsdb:
    create: true
    host: codacy-hotspotsdb.codacy.svc.cluster.local
    postgresqlUsername: codacy
    postgresqlDatabase: hotspots
    postgresqlPassword: codacy
    service:
      port: 5432

## YOU ARE NOT ADVISED TO CHANGE BEYOND THIS POINT
## Defaults for Internal Storage coming from requirements
## These values are ignored if 'create: false' in the global variables

rabbitmq-ha:
  rabbitmqUsername: "rabbitmq"
  rabbitmqPassword: "rabbitmq"

postgres:
  imageTag: "9.6.2"
  persistence:
    enabled: false
  #  storageClass:
  #  size: 20Gi
  #resources:
  #  requests:
  #    memory: 1024Mi
  #    cpu: 1000m
  initdbScripts:
    initdb.sql: |
      CREATE USER codacy WITH PASSWORD 'codacy';
      ALTER ROLE codacy WITH CREATEDB;
      CREATE DATABASE accounts WITH OWNER=codacy;
      CREATE DATABASE analysis WITH OWNER=codacy;
      CREATE DATABASE results WITH OWNER=codacy;
      CREATE DATABASE results201709 WITH OWNER=codacy;
      CREATE DATABASE metrics WITH OWNER=codacy;
      CREATE DATABASE filestore WITH OWNER=codacy;
      CREATE DATABASE jobs WITH OWNER=codacy;

minio:
  persistence:
    size: 20Gi
  minioConfig:
    region: "eu-west-1"

codacy-api:
  config:
    play:
      configFile: "enterprise.conf"