global:
  codacy:
    crow:
      url: <--- "http://codacy.example.com/monitoring" ---> # Crow URL
crow:
  replicaCount: 1
  fullnameOverride: codacy-crow
  crowdb:
    create: false
    host: <--- codacy-db-host --->
    postgresqlUsername: <--- codacy-db-username --->
    postgresqlDatabase: "crow" # You need to create the DB manually
    postgresqlPassword: <--- codacy-db-password --->
    service:
      port: 5432
    fullnameOverride: codacy-crowdb
  config:
    play:
      http:
        context: "/monitoring"
    passwordAuth:
      password: <--- crow-password --->
