## For guidance on how to setup tls please refer to the documentation on https://codacy.github.io/chart

codacy-ingress:
  create: true
  ingress:
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      kubernetes.io/ingress.class: nginx-codacy
      kubernetes.io/tls-acme: "true"
      cert-manager.io/issuer: letsencrypt-codacy
      acme.cert-manager.io/http01-edit-in-place: "true"

    hostname:
      app: <--- codacy.example.com ---> # Codacy application DNS hostname
      api: <--- codacy.example.com ---> # Codacy API DNS hostname

    hosts:
      - host: <--- codacy.example.com ---> # Codacy application DNS hostname
        paths:
          - /
    tls:
      secretName: codacy-tls
      hosts:
        - host: <--- codacy.example.com ---> # Codacy application DNS hostname
          paths:
            - /
