global:
  codacy:
    url: "http://localhost:9000"
    backendUrl: "http://localhost:9000"
    api:
      url: "codacy-api"
    portal:
      url: "codacy-portal"
    hotspots:
      url: "codacy-hotspots-api"
    engine:
      url: "codacy-engine"
    listener:
      url: "codacy-listener"
    activities:
      url: "codacy-activities"
    core:
      url: "codacy-core"
    remoteProviderService:
      url: "codacy-remote-provider-service"
    workerManager:
      url: "codacy-worker-manager"

  githubEnterprise: {}
    # if you set this provider configuration, you must save it on the admin/integrations ui.
    # enabled: "false"
    # hostname: "example.host.com"
    # port: 443
    # protocol: "https"
    # disableSSL: "false"
    # isPrivateMode: "true"

  gitlabEnterprise: {}
    # if you set this provider configuration, you must save it on the admin/integrations ui.
    # enabled: "false"
    # hostname: "example.host.com"
    # protocol: "https"
    # port: 443

  bitbucketEnterprise: {}
    # if you set this provider configuration, you must save it on the admin/integrations ui.
    # enabled: "false"
    # hostname: "example.host.com"
    # protocol: "http"
    # port: 7990

  play:
    cryptoSecret: "PLEASE_CHANGE_ME" # Generate one with `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1`

  filestore:
    contentsSecret: "PLEASE_CHANGE_ME" # Generate one with `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1`
    uuidSecret: "PLEASE_CHANGE_ME" # Generate one with `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1`

  cacheSecret: "PLEASE_CHANGE_ME" # Generate one with `cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1`

  minio:
    create: true
    location: codacy-minio
    port: 9000
    accessKey: "AKIAIOSFODNN7EXAMPLE"
    secretKey: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

  s3:
    bucket:
      analysis:
        name: "analysis"
      coverage:
        name: "coverage"
      cliReports:
        name: "cli-reports"

  rabbitmq:
    create: true
    rabbitmqUsername: rabbitmq
    rabbitmqPassword: rabbitmq
    rabbitmqvHost: "/"
    host: codacy-rabbitmq-ha
    port: 5672
    ssl: false
    timeout: 15s

  defaultdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: accounts
    postgresqlPassword: codacy
    host: codacy-postgres
    service:
      port: 5432

  analysisdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: analysis
    postgresqlPassword: codacy
    host: codacy-postgres
    service:
      port: 5432

  resultsdb201709:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: results
    postgresqlPassword: codacy
    host: codacy-postgres
    service:
      port: 5432

  metricsdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: metrics
    postgresqlPassword: codacy
    host: codacy-postgres
    service:
      port: 5432

  filestoredb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: filestore
    postgresqlPassword: codacy
    host: codacy-postgres
    service:
      port: 5432

  jobsdb:
    create: true
    imageTag: "9.6.2"
    postgresqlUsername: codacy
    postgresqlDatabase: jobs
    postgresqlPassword: codacy
    host: codacy-postgres
    service:
      port: 5432

portal:
  replicaCount: 1
  fullnameOverride: codacy-portal

activities:
  replicaCount: 1
  fullnameOverride: codacy-activities
  activitiesdb:
    create: true
    host: codacy-activitiesdb
    postgresqlUsername: "codacy"
    postgresqlDatabase: "activities"
    postgresqlPassword: "PLEASE_CHANGE_ME"
    service:
      port: 5432
    fullnameOverride: codacy-activitiesdb

remote-provider-service:
  replicaCount: 1
  fullnameOverride: codacy-remote-provider-service

hotspots-api:
  replicaCount: 1
  fullnameOverride: codacy-hotspots-api
  hotspotsdb:
    create: true
    host: codacy-hotspotsdb
    postgresqlUsername: codacy
    postgresqlDatabase: hotspots
    postgresqlPassword: codacy
    service:
      port: 5432
    fullnameOverride: codacy-hotspotsdb

hotspots-worker:
  replicaCount: 1
  fullnameOverride: codacy-hotspots-worker

listener:
  replicaCount: 1
  fullnameOverride: codacy-listener
  config:
    play:
      configFile: application.enterprise.conf
      logFile: logback.xml

  persistence:
    claim:
      size: 100Gi

  nfsserverprovisioner:
    enabled: true
    persistence:
      enabled: true
      size: 120Gi
    # resources:
    #  limits:
    #    cpu: 2
    #    memory: 4Gi
    #  requests:
    #    cpu: 0.5
    #  memory: 1Gi

  listenerdb:
    create: true
    host: codacy-listenerdb
    postgresqlUsername: "codacy"
    postgresqlDatabase: "listener"
    postgresqlPassword: "PLEASE_CHANGE_ME"
    service:
      port: 5432
    fullnameOverride: codacy-listenerdb

core:
  replicaCount: 1
  fullnameOverride: codacy-core
  config:
    play:
      configFile: "enterprise.conf"

engine:
  replicaCount: 1
  fullnameOverride: codacy-engine
  config:
    environment: enterprise
    play:
      configFile: 'enterprise-engine.conf'
      logFile: 'logback.xml'
  metrics:
    serviceMonitor:
      enabled: false
    grafana_dashboards:
      enabled: false

codacy-api:
  replicaCount: 1
  fullnameOverride: codacy-api
  config:
    # Trial license. Valid for 4 users until the end of 2020
    license: "RAjlCYb/DxsAME0TjIn55neFSYOt0yxxnXBh4nKe/hbz4mjr0dDs3TLOehzQ3QyaLfONRva7T2iSkA57bMdpI/ZwAOUQtjO5XiU1KDaSUXCFZwDu1mBJMlMONCVOV3AuB6y56tsL0CZXnBqZD3R9dShTVXiSYDt/+2dhlVqGb70="
    play:
      configFile: "enterprise.conf"
  metrics:
    serviceMonitor:
      enabled: false
    grafana_dashboards:
      enabled: false

worker-manager:
  replicaCount: 1
  fullnameOverride: codacy-worker-manager
  config:
    play:
      configFile: enterprise.conf
    cloudAmqp:
      workerUser: "rabbitmq"
      workerPass: "rabbitmq"
    workers:
      genericMax: 5
      dedicatedMax: 5
      analysis:
        # Ignore files with size bigger than this value during analysis
        maxFileSizeBytes: 150000
      # Toleration and nodeSelector for worker/tool pods
      tolerations: []
      nodeSelector: {}

    # The resources to assign to a worker pod
    workerResources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 1
        memory: 2Gi

    # The resources to assign to a tool pod
    pluginResources:
      requests:
        cpu: 0.5
        memory: 1000000000 # this value needs to be set in bytes
      limits:
        cpu: 1
        memory: 3000000000 # this value needs to be set in bytes

crow:
  replicaCount: 1
  fullnameOverride: codacy-crow
  crowdb:
    create: true
    host: codacy-crowdb
    postgresqlUsername: "codacy"
    postgresqlDatabase: "crow"
    postgresqlPassword: "PLEASE_CHANGE_ME"
    service:
      port: 5432
    fullnameOverride: codacy-crowdb

## If you set this to be enabled: true, you must clean up the fluentd job yourself
fluentdoperator:
  enabled: false
  defaultConfigmap: codacy-fluentd-config
  bucketName: fluentd-bucket
  expirationDays: 14
  rbac:
    create: true

## YOU ARE NOT ADVISED TO CHANGE BEYOND THIS POINT
## Defaults for Internal Storage coming from requirements
## These values are ignored if 'create: false' in the global variables

rabbitmq-ha:
  fullnameOverride: codacy-rabbitmq-ha
  rabbitmqUsername: "rabbitmq"
  rabbitmqPassword: "rabbitmq"

postgres:
  fullnameOverride: codacy-postgres
  imageTag: "9.6.2"
  persistence:
    enabled: false
    # storageClass:
    # size: 20Gi
  #resources:
  #  requests:
  #    memory: 1024Mi
  #    cpu: 1000m
  postgresqlExtendedConf: {"sharedBuffers": "256MB", "maxConnections": "300"}
  initdbScripts:
    initdb.sql: |
      CREATE USER codacy WITH PASSWORD 'codacy';
      ALTER ROLE codacy WITH CREATEDB;
      CREATE DATABASE accounts WITH OWNER=codacy;
      CREATE DATABASE analysis WITH OWNER=codacy;
      CREATE DATABASE results WITH OWNER=codacy;
      CREATE DATABASE metrics WITH OWNER=codacy;
      CREATE DATABASE filestore WITH OWNER=codacy;
      CREATE DATABASE jobs WITH OWNER=codacy;

minio:
  fullnameOverride: codacy-minio
  image:
    # We require this version in order to use lifecycle policies
    tag: RELEASE.2019-10-12T01-39-57Z
  persistence:
    size: 20Gi
  minioConfig:
    region: "eu-west-1"

ragnaros:
  fullnameOverride: codacy-ragnaros
